version: '3.4'

networks:
  raftel-network:
    driver: bridge

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - raftel-network

  bookify-db: 
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlServer_Docker2023"
      ACCEPT_EULA: "Y"
    networks:
      - raftel-network
